### ISSUE TITLE
Support numerical data types to count digits

### ISSUE THREAD

**Issue by psuong** [InitialPrefabs/UGUIDOTS#54]
Right now text is represented as unicode characters in a `DynamicBuffer<CharElement>()`. One way to copy a string to the DynamicBuffer is to do the following:

```cs
fixed(char* ptr = "some_string") {
  UnsafeUtility.MemCpy(destination_buffer, ptr, "some_string".Length);
}
```

The problem is that it still uses the string class. As an alternative I've started to write some utility functions to store the character elements into a ptr and length that you pass into it.

```cs
public static void ToCharArray(this int value, char* ptr, in int length, out int count) 
```

# TODO
* [ ] Add support for Unity's `FixedString` data structures
* [ ] Add support to copy from the ptr to the `DynamicBuffer<CharElement>()`
* [ ] Add support to copy from a `FixedString` to the `DynamicBuffer<CharElement>()`
* [ ] Add support for floating points

**Comment by psuong** [comment]
Did a little test with using fixed ptr and Bursted lambda expressions - looks like Unity is able to translate string formats into fixed char ptrs. I'll need to do further investigation, but here is an example of how it's done:

```cs
using UGUIDOTS.Common;
using Unity.Entities;

namespace UGUIDOTS.Sample.Systems {
    public class FPSCounterSystem : SystemBase {
        protected unsafe override void OnUpdate() {
            var timeData = Time.DeltaTime;

            Entities.WithAll<DynamicTextTag>().ForEach((DynamicBuffer<CharElement> b0) => {
                int fps = (int)(1f / timeData);

                char* ptr = (char*)b0.GetUnsafePtr();
                fps.ToCharArray(ptr, b0.Length, out int count);
            }).Run();
        }
    }
}
```

**Comment by psuong** [comment]
Referring to this post I put here as I try to figure things out: https://github.com/InitialPrefabs/UGUIDOTS/discussions/66
